blank_issues_enabled: false
contact_links:
  - name: 💬 Preguntas y Discusión Técnica
    url: https://github.com/Jonas-a1105/SGEN-Support/discussions
    about: Haz preguntas, debate sobre arquitectura o comparte ideas con el equipo.
